add more friendly stuff
jbrooksuk/SublimeFlatColors pull request #2
Opened 2016-09-17 00:56 UTC by math2001

- add your plugin to the command pallete (list color)
- when you type a color name, it inserts it hex code.
- add different source (scss, sass, stylus, postcss)
- show hex code in completions popup

Matt

2016-09-21 17:02 UTC, jbrooksuk commented on flatcolors.sublime-commands
> +	{
Can you use spaces and not tabs please.

2016-09-21 17:03 UTC, jbrooksuk requested changes
We always use spaces.

2016-09-23 06:18 UTC, math2001 commented
Hey!
I've just commited my changes, and pused them. Do I need to do something more? I'm not used for now to this kind a stuff.

2016-09-28 04:32 UTC, math2001 commented on flatcolors.sublime-commands
> +	{
Yes! I did a commit with the change.

2016-09-28 07:04 UTC, merged

2016-10-10 17:07 UTC, Kristinita commented
@jbrooksuk , please do not forget to do [releases](https://packagecontrol.io/docs/submitting_a_package#Step_4) for your plugins, so that users of your plugins received changes. Thanks.